services:
  # Postgres - Database
  postgres:
    image: ankane/pgvector
    container_name: postgres
    hostname: postgres
    restart: always
    networks:
      - default
    ports:
      - "5432:5432"
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ../appdata/postgres/data:/var/lib/postgresql/data
